name: TOC Generator

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  toc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/toc-generator@v4
